---
- hosts: all
  gather_facts: false
  
# uncomment this if you want manually enter your credentials for vSphere
#  vars_prompt:
#    - name: "vsphere_host"
#      promt: "vSphere host"
#      private: no
##      default: "esxi.example.com"
#    - name: "vsphere_user"
#      prompt: "vSphere Username"
#      private: no
##      default: "root"
#    - name: "vsphere_password"
#      prompt: "vSphere Password"
##      default: "Pa$sw0rD"
#    - name: "cluster"
#      promt: "Cluster to deploy"
#      private: no
##      default: "esxi.example.com"
#    - name: "notes"
#      prompt: "VM notes"
#      private: no
##      default: "Deployed with ansible playbook"

  roles:
     - deploy_vmware_guest


