---
- hosts: all
  gather_facts: false
  
#  vars_prompt:
#    - name: "vsphere_host"
#      promt: "vSphere host"
#      private: no
##      default: "esxi.shuliakovsky.com"
#    - name: "vsphere_user"
#      prompt: "vSphere Username"
#      private: no
##      default: "root"
#    - name: "vsphere_password"
#      prompt: "vSphere Password"
##      default: "R0yatnrf123$"
#    - name: "cluster"
#      promt: "Cluster to deploy"
#      private: no
##      default: "esxi.shuliakovsky.com"
#    - name: "notes"
#      prompt: "VM notes"
#      private: no
##      default: "Deployed with ansible playbook"

  roles:
     - remove_vmware_guest


