---
# Usage ansible-playbook -i hosts deploy_vmware_guests.yml --forks=1 --ask-vault-pass... to correct dhcpd.conf update

- name: Gather facts about deployed VMs
  tags: removevm, configupdate, dhcpupdate, dnsupdate
  vmware_guest_facts:
    hostname: '{{ vsphere_host }}'
    username: '{{ vsphere_user }}'
    password: '{{ vsphere_password }}'
    datacenter: '{{ cluster }}'
    validate_certs: no
    name: '{{ inventory_hostname }}'
  delegate_to: localhost
  register: vminfo
  ignore_errors: yes

- name: stdout
  tags: removevm, configupdate, dhcpupdate, dnsupdate
  debug: var=vminfo
  with_items: vminfo

- name: Update dhcp config
  tags: removevm, configupdate, dhcpupdate
  vars:
    host:
      name: '{{ vminfo.instance.hw_name }}'
      mac: '{{ vminfo.instance.hw_eth0.macaddress }}'
      ip: '{% if not vminfo.instance.hw_eth0.ipaddresses %}{{ vminfo.instance.ipv4 }}{% else %}{{ vminfo.instance.hw_eth0.ipaddresses[0] }}{% endif %}'
  blockinfile:
    state: absent
    path: |-
            /etc/dhcp/hosts/{% if not host.ip %}{{ host_ip.split('.')[0:3]| join('.') }}{%  else %}
            {{ host.ip.split('.')[0:3]| join('.') }}{% endif %}.255.conf
    backup: no
    marker: "# {mark} {{ host.name}} {{ notes }}"
    marker_end: "#END"
    block: |
     host {{ host.name }} {
       hardware ethernet {{ host.mac }};
       fixed-address {% if not host.ip %}{{ host_ip }}{% else %}{{ host.ip }}{% endif %};}
    validate: dhcpd -t -cf %s
    insertafter: EOF
  delegate_to: "{{ dhcp_host }}"

- name: Update master dns config
  tags: removevm, configupdate, dnsupdate
  vars:
    host:
      name: '{{ vminfo.instance.hw_name }}'
      mac: '{{ vminfo.instance.hw_eth0.macaddress }}'
      ip: '{% if not vminfo.instance.hw_eth0.ipaddresses %}{{ vminfo.instance.ipv4 }}{% else %}{{ vminfo.instance.hw_eth0.ipaddresses[0] }}{% endif %}'

  lineinfile:
    state: absent
    insertafter: EOF
    dest: '/var/named/master/local_shuliakovsky.com.dns'
    line: "{{ inventory_hostname.split('.')[0]}}\t\t\tIN\tA\t{% if not host.ip %}{{ host_ip }}{%  else %}{{ host.ip }}{% endif %}"
    backup: no
  delegate_to: "{{ dns_host }}"

- name: Update reverse DNS
  tags: removevm, configupdate, dnsupdate
  vars:
    host:
      name: '{{ vminfo.instance.hw_name }}'
      mac: '{{ vminfo.instance.hw_eth0.macaddress }}'
      ip: '{% if not vminfo.instance.hw_eth0.ipaddresses %}{{ vminfo.instance.ipv4 }}{% else %}{{ vminfo.instance.hw_eth0.ipaddresses[0] }}{% endif %}'

  lineinfile:
    state: absent
    insertafter: EOF
    dest: '/var/named/rev/1.168.192.in-addr.arpa.dns'
    line: "{% if not host.ip %}{{ host_ip.split('.')[-1]}}{%  else %}{{ host.ip.split('.')[-1] }}{% endif %}\t\tIN\tPTR\t{{  inventory_hostname  }}."
    backup: no
  delegate_to: "{{ dns_host }}"

- name: restart dhcpd
  service: name=dhcpd state=restarted
  run_once: true
  delegate_to: "{{ dhcp_host }}"
  tags: removevm, configupdate, dhcpupdate

- name: restart named
  service: name=named state=restarted
  run_once: true
  delegate_to: "{{ dns_host }}"
  tags: removevm, configupdate, dnsupdate

- name: remove VM
  tags: removevm
  vmware_guest:
    hostname: '{{ vsphere_host }}'
    username: '{{ vsphere_user }}'
    password: '{{ vsphere_password }}'
    validate_certs: no
    #cluster: '{{ cluster }}'
    #when: esxi_hostname == ""
    esxi_hostname: '{{ cluster }}'
    #when: cluster == ""
    #datacenter: '{{ datacenter }}'
    #datacenter: '{{ cluster }}'
    folder: '{{  vsphere_folder  }}'
    name: '{{ inventory_hostname }}'
    state: "{{ items }}"
    #guest_id: '{{ guest_id }}'

  delegate_to: localhost
  ignore_errors: yes
  with_items: poweredoff, absent


