---
# Usage ansible-playbook -i hosts deploy_vmware_guests.yml --forks=1 --ask-vault-pass... to correct dhcpd.conf update

- name: Gather facts about deployed VMs
  tags: removevm, configupdate, dhcpupdate, dnsupdate
  vmware_guest_facts:
    hostname: '{{ vsphere_host }}'
    username: '{{ vsphere_user }}'
    password: '{{ vsphere_password }}'
    datacenter: '{{ vsphere_check_config }}'
    validate_certs: no
    name: '{{ inventory_hostname }}'
  delegate_to: localhost
  register: vminfo
  ignore_errors: yes

- name: stdout
  tags: removevm, configupdate, dhcpupdate, dnsupdate
  debug: var=vminfo
  with_items: vminfo

- name: Update dhcp config
  tags: removevm, configupdate, dhcpupdate
  vars:
    host:
      name: '{{ vminfo.instance.hw_name }}'
      mac: '{{ vminfo.instance.hw_eth0.macaddress }}'
      ip: '{% if not vminfo.instance.hw_eth0.ipaddresses %}{{ vminfo.instance.ipv4 }}{% else %}{{ vminfo.instance.hw_eth0.ipaddresses[0] }}{% endif %}'
  blockinfile:
    state: absent
    path: |-
            {{ dhcp_conf_folder }}{% if not host.ip %}{{ host_ip.split('.')[0:3]| join('.') }}{%  else %}
            {{ host.ip.split('.')[0:3]| join('.') }}{% endif %}.255.conf
    backup: no
    marker: "# {mark} {{ host.name}} {{ notes }}"
    marker_end: "#END"
    block: |
     host {{ host.name }} {
       hardware ethernet {{ host.mac }};
       fixed-address {% if not host.ip %}{{ host_ip }}{% else %}{{ host.ip }}{% endif %};}
    validate: dhcpd -t -cf %s
    insertafter: EOF
  delegate_to: "{{ dhcp_host }}"

- name: Update master dns config
  tags: removevm, configupdate, dnsupdate
  vars:
    host:
      name: '{{ vminfo.instance.hw_name }}'
      mac: '{{ vminfo.instance.hw_eth0.macaddress }}'
      ip: '{% if not vminfo.instance.hw_eth0.ipaddresses %}{{ vminfo.instance.ipv4 }}{% else %}{{ vminfo.instance.hw_eth0.ipaddresses[0] }}{% endif %}'

  lineinfile:
    state: absent
    insertafter: EOF
    dest: '{{ primary_dns_file }}' #your dns filename
    line: "{{ inventory_hostname.split('.')[0]}}\t\t\tIN\tA\t{% if not host.ip %}{{ host_ip }}{%  else %}{{ host.ip }}{% endif %}"
    backup: no
  delegate_to: "{{ dns_host }}"

- name: Update reverse DNS
  tags: removevm, configupdate, dnsupdate
  vars:
    host:
      name: '{{ vminfo.instance.hw_name }}'
      mac: '{{ vminfo.instance.hw_eth0.macaddress }}'
      ip: '{% if not vminfo.instance.hw_eth0.ipaddresses %}{{ vminfo.instance.ipv4 }}{% else %}{{ vminfo.instance.hw_eth0.ipaddresses[0] }}{% endif %}'

  lineinfile:
    state: absent
    insertafter: EOF
    dest: '{{ reverse_dns_file }}'
    line: "{% if not host.ip %}{{ host_ip.split('.')[-1]}}{%  else %}{{ host.ip.split('.')[-1] }}{% endif %}\t\tIN\tPTR\t{{  inventory_hostname  }}."
    backup: no
  delegate_to: "{{ dns_host }}"

- name: restart dhcpd
  service: name=dhcpd state=restarted
  run_once: true
  delegate_to: "{{ dhcp_host }}"
  tags: removevm, configupdate, dhcpupdate

- name: restart named
  service: name=named state=restarted
  run_once: true
  delegate_to: "{{ dns_host }}"
  tags: removevm, configupdate, dnsupdate

- name: remove VM
  tags: removevm
  vars:
    check_check_config: '{% if vsphere_datacenter is defined %}vmare_guest.datacenter: {{ vspere_datacenter }}vmware_guest.check_config: {{ vsphere_check_config }}{% else %}vmare_guest.esxi_hostname:{{  vsphere_check_config  }}{% endif %}'
  vmware_guest:
    hostname: '{{ vsphere_host }}'
    username: '{{ vsphere_user }}'
    password: '{{ vsphere_password }}'
    validate_certs: no
    folder: '{{  vsphere_folder  }}'
    name: '{{ inventory_hostname }}'
    state: '{{ item }}'
  with_items:
    - poweredoff
    - absent
    #guest_id: '{{ guest_id }}'
  delegate_to: localhost
  ignore_errors: yes


